-- DDL DATABASE DEFINITION LANGUAGE


-- PROJETO HEALTH CLINIC

CREATE DATABASE Health_Clinic_Manha

USE Health_Clinic_Manha




CREATE TABLE TipoUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Especialidade
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE [Status]
(
	IdStatus INT PRIMARY KEY IDENTITY,
	StatusDaConsulta VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	NomeFantasia VARCHAR (256) NOT NULL,
	RazaoSocial VARCHAR (256) NOT NULL,
	Endereco VARCHAR(256) NOT NULL,
	HorarioAbertura TIME NOT NULL,
	HorarioFechamento TIME NOT NULL
)


CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Senha VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	Telefone VARCHAR(13) NOT NULL
)


CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL UNIQUE,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade) NOT NULL,
	CRM VARCHAR(50) NOT NULL UNIQUE
)


CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL
)


CREATE TABLE Consulta 
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente) NOT NULL,
	IdStatus INT FOREIGN KEY REFERENCES [Status](IdStatus) NOT NULL,
	[Data] DATE NOT NULL,
	Horario TIME(0) NOT NULL
)


CREATE TABLE Prontuario
(
	IdProntuario INT PRIMARY KEY IDENTITY,
	IdConsulta INT FOREIGN KEY REFERENCES Consulta(IdConsulta) NOT NULL UNIQUE,
	HistoricoMedico VARCHAR(256) NOT NULL,
	Medicamento VARCHAR(256) NOT NULL,
	PlanoTratamento VARCHAR(256) NOT NULL
)


CREATE TABLE Comentario
(
	IdComentario INT PRIMARY KEY IDENTITY,
	IdConsulta INT FOREIGN KEY REFERENCES Consulta(IdConsulta) NOT NULL,
	Descricao VARCHAR(256) NOT NULL,
	Exibir BIT DEFAULT 0
)


DROP TABLE Consulta